version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server1
      - server2
    networks:
      - app_network

  server1:
    build:
      context: ./server1
    ports:
      - "3001:3001"
    environment:
      - CASSANDRA_HOST=cassandra
    depends_on:
      - cassandra
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/data"]
      interval: 30s
      timeout: 10s
      retries: 5

  server2:
    build:
      context: ./server2
    ports:
      - "3002:3002"
    environment:
      - CASSANDRA_HOST=cassandra
    depends_on:
      - cassandra
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/data"]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    networks:
      - app_network
    volumes:
      - cassandra_data:/var/lib/cassandra

networks:
  app_network:
    driver: bridge

volumes:
  cassandra_data:
